env:
  global:
    - CC_TEST_REPORTER_ID=c3d0f661ee7af0f84e0ef70a7d353e5cf04db279182ac355c0a91632dc8be92f

language: node_js

node_js:
    - "node"
    - "10"
    - "8"

sudo: false

git:
    submodules: false

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - npm install

script:
    - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
