version: "3"
services:
    node9:
        image: "emsa16/ramverk2-me:node9"
        build:
            context: .
            dockerfile: node9/Dockerfile
        ports:
            - "8093:8099"
    node8:
        image: "emsa16/ramverk2-me:node8"
        build:
            context: .
            dockerfile: node8/Dockerfile
        ports:
            - "8089:8099"
    node6:
        image: "emsa16/ramverk2-me:node6"
        build:
            context: .
            dockerfile: node6/Dockerfile
        ports:
            - "8061:8099"
